---
pgcat_user: "pgcat"
pgcat_group: "pgcat"
pgcat_repo_url: "https://github.com/postgresml/pgcat.git"
pgcat_repo_version: "main"
pgcat_source_dir: "/usr/local/src/pgcat"
pgcat_config_dir: "/etc/pgcat"
pgcat_config_file: "{{ pgcat_config_dir }}/pgcat.toml"
pgcat_binary: "/usr/local/bin/pgcat"
pgcat_service: "pgcat"
pgcat_listen_address: "0.0.0.0"
pgcat_port: "{{ proxy_pg_rw_port | default(5432) }}"
pgcat_admin_port: "{{ proxy_admin_port | default(9930) }}"
pgcat_admin_user: "admin"
pgcat_database: "postgres"
pgcat_pool_mode: "transaction"
