---
pgpool_package: "pgpool2"
pgpool_service: "pgpool2"
pgpool_config_dir: "/etc/pgpool2"
pgpool_config_file: "{{ pgpool_config_dir }}/pgpool.conf"
pgpool_pool_hba_file: "{{ pgpool_config_dir }}/pool_hba.conf"
pgpool_pcp_file: "{{ pgpool_config_dir }}/pcp.conf"

pgpool_listen_addresses: "*"
pgpool_port: "{{ proxy_pg_rw_port | default(5432) }}"
pgpool_pcp_port: "{{ proxy_admin_port | default(9898) }}"
pgpool_health_check_period: 10
pgpool_health_check_timeout: 20
pgpool_health_check_max_retries: 3
